version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "studoc-backend"
    AWS_REGION: "us-east-1"
  runtime-versions:
    docker: 20

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
      - echo ECR_URI=$ECR_URI
  build:
    commands:
      - echo Build Docker image for backend...
      - cd backend
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest $ECR_URI:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_URI:latest
artifacts:
  files:
    - '**/*'
