AWSTemplateFormatVersion: "2010-09-09"
Description: ECR repositories for StuDoc (backend + frontend)

Resources:

  BackendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: studoc-backend
      ImageTagMutability: MUTABLE
      EncryptionConfiguration:
        EncryptionType: AES256

  FrontendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: studoc-frontend
      ImageTagMutability: MUTABLE
      EncryptionConfiguration:
        EncryptionType: AES256

Outputs:
  BackendRepoUri:
    Description: ECR URI for backend repository
    Value: !GetAtt BackendRepository.RepositoryUri

  FrontendRepoUri:
    Description: ECR URI for frontend repository
    Value: !GetAtt FrontendRepository.RepositoryUri
