AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Fargate service for StuDoc frontend

Parameters:
  ClusterName:
    Type: String
  ServiceSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  Subnet1:
    Type: AWS::EC2::Subnet::Id
  Subnet2:
    Type: AWS::EC2::Subnet::Id
  FrontendImageUri:
    Type: String
    Description: ECR image URI for the frontend
  FrontendTargetGroupArn:
    Type: String

Resources:
  StuDocFrontendTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: studoc-frontend-task
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: X86_64
      ContainerDefinitions:
        - Name: studoc-frontend
          Image: !Ref FrontendImageUri
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          Essential: true

  StuDocFrontendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: studoc-frontend-service
      Cluster: !Ref ClusterName
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ServiceSecurityGroupId
          Subnets:
            - !Ref Subnet1
            - !Ref Subnet2
      LoadBalancers:
        - ContainerName: studoc-frontend
          ContainerPort: 80
          TargetGroupArn: !Ref FrontendTargetGroupArn
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50

Outputs:
  FrontendServiceName:
    Description: Name of the ECS frontend service
    Value: !Ref StuDocFrontendService
