AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Cluster for StuDoc

Resources:
  StuDocCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: studoc-cluster

Outputs:
  ClusterName:
    Description: Name of the ECS cluster
    Value: !Ref StuDocCluster
